Music Tribes/Musictribes/urls.py
from django.contrib import admin
from django.contrib.auth import views as auth_views
from django.urls import path, include
from User import views as user_views
from django.conf import settings
from django.conf.urls.static import static



urlpatterns = [
    path('', include('Tribes.urls')),
    path('admin/', admin.site.urls),
    path('profile/', user_views.profile, name='profile'),
    path('register/', user_views.register, name='register'),
    path('login/', auth_views.LoginView.as_view(template_name='User/login.html'), name='login'),
    path('logout/', auth_views.LogoutView.as_view(template_name='User/logout.html'), name='logout'),
    

    
]

if settings.DEBUG:
    
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)

Music Tribes/Tribes/urls.py
from django.urls import path
from . import views
from .views import (
    TribeCreateView,
    TribeDetailView, 
    TribeUpdateView,
    TribeDeleteView,
    TribeListView,
    PlaylistCreateView,
    PlaylistUpdateView,
    PlaylistDeleteView,
    ConversationView,
    PlaylistDetailView,
    SongCreateView,
    SongDeleteView
)


app_name= 'tribe'

urlpatterns = [
    path('', TribeListView.as_view(), name='home'),

    path('tribe/new/', TribeCreateView.as_view(), name='tribe-create'),
    path('chat/<int:id>/', ConversationView.as_view(), name='chat_conversation' ),
    path('tribe/<int:pk>/', TribeDetailView.as_view(), name='detail'),
    path('tribe/<int:pk>/update/', TribeUpdateView.as_view(), name='update'),
    path('tribe/<int:pk>/delete/', TribeDeleteView.as_view(), name='delete'),

    path('join/<int:pk>', views.join, name='join'),
    path('leave/<int:pk>', views.leave, name='leave'),
    path('kick/<int:id1>/<int:id2>/', views.kick, name='kick'),

    path('playlist/<int:pk>/new', PlaylistCreateView.as_view(), name='create-playlist'),
    path('playlist/<int:pk>/update/', PlaylistUpdateView.as_view(), name='update-playlist'),
    path('playlist/<int:pk>/delete/', PlaylistDeleteView.as_view(), name='delete-playlist'),
    path('tribe/playlist/<int:pk>/', PlaylistDetailView.as_view(), name='playlist'),

    path('deletemsg/<int:id1>/<int:id2>/<str:text>', views.delete_message, name='delete-msg'),

    path('playlist/song/new/<int:pk>', SongCreateView.as_view(), name='song-create'),
    path('song/<int:pk>/delete/', SongDeleteView.as_view(), name='song-delete'),
    path('song-like/<int:pk>', views.like, name="song-like"),
    
    path('comment/<int:tribe_id>/<int:playlist_id>/<int:song_id>', views.comment, name='comment'),	
    path('delete-comment/<int:tribe_id>/<int:playlist_id>/<int:comment_id>', views.delete_comment, name='delete-comment'),	
    
]

Music Tribes/Tribes/models.py
from django.utils import timezone
from django.db import models
from django.contrib.auth.models import User
from django.urls import reverse
from PIL import Image
from django.shortcuts import redirect 

class Tribes(models.Model):
    
    title = models.CharField(max_length=100)
    chief = models.ForeignKey(User, on_delete=models.CASCADE, related_name='chief')
    image= models.ImageField(upload_to='tribes_pics',  verbose_name="")
    genre = models.CharField(max_length=64)
    members = models.ManyToManyField(User, through='Membership')
    post_date = models.DateTimeField(default=timezone.now, blank=True)
    
    


    def __str__(self):
        return self.title
    def get_absolute_url(self):
        return reverse('tribe:detail', kwargs={'pk': self.pk})



class Membership(models.Model):
    person = models.ForeignKey(User, on_delete=models.CASCADE)
    group = models.ForeignKey(Tribes, on_delete=models.CASCADE)
    date_joined = models.DateField()
    def __str__(self):
        return "Member: {} in Tribe: {}".format(self.person, self.group)  



class Playlist(models.Model):
   user = models.ForeignKey(User, on_delete=models.CASCADE )
   tribe = models.ForeignKey(Tribes, on_delete=models.CASCADE)
   name = models.CharField(max_length=64)
   description = models.CharField(max_length=256)
   date_created = models.DateTimeField(default=timezone.now, blank=True)
   
   def __str__(self):
      return "playlist: {}, from tribe: {}".format(self.name, self.tribe)   
   def get_absolute_url(self):
       tribe = self.tribe
       return reverse('tribe:detail', kwargs={'pk': tribe.pk})





class  Conversation(models.Model):
	sender = models.ForeignKey(User, on_delete=models.CASCADE, related_name='sender')
	receiver = models.ForeignKey(Tribes, on_delete=models.CASCADE, related_name='receiver')
	text = models.TextField()
	created_time = models.DateTimeField(auto_now_add=True,)

	def __str__(self):
		return "from {} to {}".format(self.sender, self.receiver)            


class Song(models.Model):
    title = models.CharField(max_length=150)
    playlist = models.ForeignKey(Playlist, on_delete=models.CASCADE)
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    artist = models.CharField(max_length=150)
    youtube_url = models.CharField(max_length=512)
    duration = models.FloatField(default=0.0)
    likes = models.ManyToManyField(User, related_name='like', default=0)

    def get_absolute_url(self):
        playlist = self.playlist
        return reverse('tribe:playlist', kwargs={'pk': playlist.pk})
    def __str__(self):
	    return " {}, song: {}".format(self.playlist, self.title)          

class Comment(models.Model):
    user = models.ForeignKey(User, on_delete=models.CASCADE)
    song = models.ForeignKey(Song, on_delete=models.CASCADE)
    text = models.CharField(max_length=500)
    date_created = models.DateTimeField(auto_now_add=True)
    def __str__(self):
        return "user: {}".format(self.user)       

      

Music Tribes/Tribes/forms.py
from django import forms
from django.forms import ModelForm
from .models import Conversation, Comment

class ConversationForm(forms.ModelForm):

	class Meta:
		model = Conversation
		fields = ['text']	

class CommentForm(ModelForm):
    class Meta:
        model = Comment
        fields = ['text']		

Music Tribes/Tribes/views.py
from django.http import request
from PIL import Image
from Tribes.models import Membership, Tribes, Playlist, Song, Comment
from django.contrib.auth.models import User
from django.contrib.auth.mixins import LoginRequiredMixin, UserPassesTestMixin
from django.http.response import HttpResponseRedirect
from django.urls import reverse
from django import forms
import datetime
from django.views.generic import (
    CreateView,
    DetailView, 
    UpdateView,
    DeleteView,
    ListView, 
)
from django.shortcuts import  get_object_or_404, render, redirect
from django.db.models import Q
from .models import Conversation
from .forms import CommentForm




class TribeListView(ListView):
    model = Tribes
    template_name='Tribes/home.html' #<app>/<model>_<viewtype>.html
    context_object_name = 'tribes'
    


class TribeCreateView(LoginRequiredMixin, CreateView):
    model = Tribes
    fields = ['title', 'genre','image']

    def is_limit_reached(self):
        return Tribes.objects.filter(chief=self.request.user).count() >= 1

    def form_valid(self, form):
         
        
        if self.is_limit_reached():
            
            return HttpResponseRedirect(reverse('tribe:home') +'?limit=true')
        else:
            form.instance.chief = self.request.user
            
            return super().form_valid(form)




class TribeDetailView(DetailView):
    template_name = 'Tribes/tribes_detail.html'
    model = Tribes

    
    def post(self, request, *args, **kwargs):
	    receiver = get_object_or_404(Tribes, id=kwargs.get('pk'))
	    instance = self.model.objects.create(**{
				'sender': request.user,
				'receiver': receiver,
				'text': request.POST.get('text')
			})  
    def get_context_data(self,*args,**kwargs):
        tribe_id=self.object.id
        context=super(TribeDetailView, self).get_context_data(*args,**kwargs)
        context['object_list'] = Conversation.objects.filter(receiver_id=tribe_id)
        return context          

    



class TribeUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Tribes
    fields = ['title', 'genre', 'image']

    def form_valid(self, form):
        form.instance.chief = self.request.user
        return super().form_valid(form)

    def test_func(self):
        post=self.get_object()
        if self.request.user == post.chief or self.request.user.is_staff:
            return True
        return False    




class TribeDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Tribes
    success_url= '/'

    def test_func(self):
        post=self.get_object()
        if self.request.user == post.chief or self.request.user.is_staff:
            return True
        return False 



class TribesForm(forms.ModelForm):

    class Meta:
        model = Tribes
        exclude = ['date_posted',]



class PlaylistCreateView(LoginRequiredMixin, CreateView):
    model = Playlist
    fields = ['name', 'description']

    def form_valid(self, form):
        tribe = Tribes.objects.get(id=self.kwargs['pk'])
        
        if self.request.user == tribe.chief or self.request.user.is_staff:
            form.instance.user = self.request.user
            form.instance.tribe_id = self.kwargs['pk']
            return super().form_valid(form)
        return HttpResponseRedirect(reverse('tribe:detail', kwargs={'pk': self.kwargs['pk']}) +'?limit4=true')



class PlaylistUpdateView(LoginRequiredMixin, UserPassesTestMixin, UpdateView):
    model = Playlist
    fields = ['name', 'description']

    def form_valid(self, form):
        return super().form_valid(form)

    def test_func(self):
        post=self.get_object()
        if self.request.user.is_staff or self.request.user == post.tribe.chief:
            return True
        return False   


class PlaylistDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Playlist
    

    def test_func(self):
        post=self.get_object()
        if self.request.user.is_staff or self.request.user == post.tribe.chief:
            return True
        return False 
    
    def get_success_url(self):
        return reverse('tribe:detail', kwargs={'pk': self.object.tribe.id}) 



class ConversationView(ListView):
	model = Conversation
	def get_context_data(self, *args, **kwargs):
        
		context = super().get_context_data(*args, **kwargs)
		context['tribes'] = Tribes.objects.all()
		return context

	def get_queryset(self):
		receiver = get_object_or_404(Tribes, id=self.kwargs.get('id'))
		messages = self.model.objects.filter(Q(sender=self.request.user, receiver=receiver) | Q(sender=self.request.user, receiver=receiver)).order_by('-created_time')

		return messages
	
	def post(self, request, *args, **kwargs):
	    receiver = get_object_or_404(Tribes, id=kwargs.get('id'))
	    instance = self.model.objects.create(**{
				'sender': request.user,
				'receiver': receiver,
				'text': request.POST.get('text')
			})
	    self.object_list = self.get_queryset()
	    context = self.get_context_data()
	    return HttpResponseRedirect(request.META.get('HTTP_REFERER')) 



class PlaylistDetailView(DetailView):
    
    model = Playlist
    

class SongCreateView(LoginRequiredMixin, CreateView):
    model = Song
    fields = ['title', 'artist','youtube_url','duration']

    def form_valid(self, form):
        playlist = Playlist.objects.get(id=self.kwargs['pk'])
        
        if self.request.user in playlist.tribe.members.all() or self.request.user == playlist.tribe.chief:
            song = form.save(commit=False)
            if song.youtube_url.startswith("https://www.youtube.com/"):
                form.instance.user = self.request.user
                form.instance.playlist_id = self.kwargs['pk']
                return super().form_valid(form)
            else: 
                return HttpResponseRedirect(reverse('tribe:playlist', kwargs={'pk': self.kwargs['pk']})  +'?limit2=true')
        return HttpResponseRedirect(reverse('tribe:playlist', kwargs={'pk': self.kwargs['pk']}) +'?limit3=true')    

class SongDeleteView(LoginRequiredMixin, UserPassesTestMixin, DeleteView):
    model = Song
    

    def test_func(self):
        post=self.get_object()
        if self.request.user.is_staff or self.request.user == post.playlist.tribe.chief or self.request.user == post.user:
            return True
        return False 
    
    def get_success_url(self):
        return reverse('tribe:playlist', kwargs={'pk': self.object.playlist.id})


def join(request,pk):
    
   
    new_obj = Tribes.objects.get(id=pk)
    new_obj.user = request.user 
    new_obj.save()
    if Membership.objects.filter(person=new_obj.user, group=new_obj).exists():
        return HttpResponseRedirect(reverse('tribe:home') )
    else:     
        membership = Membership.objects.create(person_id=new_obj.user.id, group = new_obj, date_joined=datetime.datetime.now())
        
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



def leave(request,pk):
    filter = Membership.objects.filter(person_id=request.user.id, group_id=pk)
    filter.delete()
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))



def kick(request,id1,id2):
    tribe = Tribes.objects.get(id=id2)
    if tribe.chief_id == request.user.id or request.user.is_staff:
        filter = Membership.objects.filter(person_id=id1, group_id=id2)
    
        filter.delete()
        return HttpResponseRedirect(reverse('tribe:detail', kwargs={'pk': tribe.id}) )    
    return HttpResponseRedirect(reverse('tribe:detail', kwargs={'pk': tribe.id}) +'?limit6=true')   


   

def delete_message(request,id1,id2,text):   
    tribe = Tribes.objects.get(id=id2)
    
    if tribe.chief_id == request.user.id or request.user.is_staff:
        filter = Conversation.objects.filter(sender_id=id1, receiver_id=id2, text=text)
    
        filter.delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER'))  
    return HttpResponseRedirect(request.META.get('HTTP_REFERER'))  



def like(request, pk):
    song = get_object_or_404(Song, id=pk)
    if request.user in song.playlist.tribe.members.all() or request.user == song.playlist.tribe.chief:
        if song.likes.filter(id=request.user.id).exists():
            song.likes.remove(request.user)
        else:
            song.likes.add(request.user)
        return HttpResponseRedirect(reverse('tribe:playlist', kwargs={'pk': song.playlist.id}) ) 
    return HttpResponseRedirect(reverse('tribe:playlist', kwargs={'pk': song.playlist.id}) +'?limit5=true') 

def comment(request, tribe_id, playlist_id, song_id):
    tribe = get_object_or_404(Tribes, pk = tribe_id)
    playlist = get_object_or_404(Playlist, pk = playlist_id)
    song = get_object_or_404(Song, pk = song_id)
    songs = Song.objects.all().filter(playlist= playlist)
    comments = Comment.objects.all().filter(song=song)
    user = request.user
    form = CommentForm(request.POST)

    if request.method == 'POST' and  user in tribe.members.all() or user == tribe.chief or user.is_staff:
        if form.is_valid():
            comment = form.save(commit=False)
            comment.user = request.user
            comment.song = song
            comment.save()
            return redirect(reverse('tribe:playlist', kwargs={ 'pk': playlist.id}))
    
    context = {
        'tribe': tribe,
        'playlist': playlist,
        'songs' : songs,
        'comments': comments,
        'form' : form
    }
    
    return render(request, 'tribe:playlist', context)


def delete_comment(request, tribe_id, playlist_id, comment_id):
    comment = get_object_or_404(Comment, pk=comment_id)
    tribe = get_object_or_404(Tribes, pk = tribe_id)
    user = request.user 
    if user == comment.user or user.is_superuser or user == tribe.chief:
        comment.delete()
        return HttpResponseRedirect(request.META.get('HTTP_REFERER')) 
    return redirect(reverse('tribe:playlist', kwargs={ 'pk': playlist_id}) + '?limit7=true')

Music Tribes/Tribes/templates/Tribes/chat.html
<html>
	<head>Chat page</head>
	<body>		
		<ul>
			{% for tribe in tribes %}
				<li>
					<a href="{% url 'tribe:chat_conversation' tribe.id %}">
						{{ tribe }}
					</a>					
				</li>
			{% endfor %}
		</ul>
	</body>
</html>

Music Tribes/Tribes/templates/Tribes/create_tribe.html
{% extends "Tribes/base.html" %}

{% load crispy_forms_tags %}

{% block content %}
    <div class="content-section">
        <div class="media">

        <div class="media-body">
            <h2 class="account-heading">{{ chief.username }}</h2>
            <p class="text-secondary">{{ chief.email }}</p>
        </div>
        </div>
        <form method="POST" enctype="multipart/form-data">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Create Your Tribe</legend>
                {{ form|crispy }}
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-info" type="submit">Update</button>
            </div>
        </form>
    </div>
{% endblock content %}
{% block list %}
{% endblock %}

Music Tribes/Tribes/templates/Tribes/playlist_confirm_delete.html
{% extends "Tribes/base.html" %}

{% block content %}
    <div class="content-section">
        <form method="POST">
            {% csrf_token %}
            <fieldset class="form-group">
                <legend class="border-bottom mb-4">Delete Playlist</legend>
                <h2>Are you sure you want to delete the playlist "{{ object.name }}"</h2>
               
            </fieldset>
            <div class="form-group">
                <button class="btn btn-outline-danger" href="{% url 'tribe:detail' object.tribe.id %}" type="submit">Yes, Delete</button>
                <a class="btn btn-outline-secondary" href="{% url 'tribe:detail' object.tribe.id %}">Cancel</a>
            </div>
        </form>
    </div>
{% endblock content %}

{% block list %}
{% endblock %}

Music Tribes/Tribes/templates/Tribes/playlist_detail.html
{% extends "Tribes/base.html" %}


{% block content %}

   <article class="media content-section">
       <div class="media-body">
         <div class="article-metadata">
            <div>
           <a class="mr-2" >Created by: {{ object.user }} at {{ object.date_created }}</a>
          
            </div>

         </div>
         <h2 class="article-title" >Playlist: <b>{{ object.name }}</b></h2>
         <p class="article-content">Description: {{ object.description }}</p>
         <h2 class="article-title" >Songs: </h2>
         {% if user in object.tribe.members.all or user == object.tribe.chief or user.is_staff  %}
         <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'tribe:song-create' pk=object.id %}" >Add Song</a>
         {% endif %}
{% for song in object.song_set.all %}
         <div style="border-style: ridge;border-color: white;border-radius: 13px;">
            
            <p class="article-content"><b>{% if user.is_staff or user == song.user or user == object.tribe.chief %}<a href="{% url 'tribe:song-delete' song.id %}" > <img style="width: 20px;height: 20px;" src="/media/icon-delete.jpg" ></a>{% endif %}{{ song.artist }} - {{ song.title }}({{song.duration}})</b> <a target="_blank" rel="noopener" href="{{ song.youtube_url }}"><img class="rounded-circle article-img" style="width:30px; height: 30px;" src="/media/play-icon.jpg" ></a>{% if user in object.tribe.members.all or user == object.tribe.chief or user.is_staff  %} {% if user in song.likes.all %}<a href="{% url 'tribe:song-like' song.id %}">Unlike<img class="rounded-circle article-img" style="width:30px; height: 30px;" src="/media/dislike-icon.jpg" ></a>{% else %}<a href="{% url 'tribe:song-like' song.id %}">Like<img class="rounded-circle article-img" style="width:30px; height: 30px;" src="/media/like-icon.jpg" ></a>{% endif %}{% endif %} <b>{{ song.likes.count }}</b></p>
         
          
         
            
         {% if song.comment_set.count == 0 %}
         
         <span style = "cursor: pointer;"class="show">Be first to comment!</span>
         {%else%}
         <span style = "cursor: pointer;"class="show">There are {{ song.comment_set.count }} comments. Check em' out!</span>
         
         {% endif %}
         
   
    <div  class="comments_section" style="display: none;" >
        {% for comment in song.comment_set.all %}
        
        
        
            <div class="list-group-item list-group-item-light">
                
                <img class="rounded-circle article-img" style="width:30px; height: 30px;" src="{{ comment.user.profile.image.url }}" >
                
                <b>{{comment.user.username}}</b>
                at {{comment.date_created}}
                {% if user.is_staff or user == comment.user or user == object.tribe.chief %}
                {% csrf_token %}
                <a href="{% url 'tribe:delete-comment' tribe_id=object.tribe.id playlist_id=object.id comment_id=comment.id %}" > <img style="width: 20px;height: 20px;" src="/media/icon-delete.jpg" ></a>
                {% endif %}
                <p style="color: black;">{{comment.text}}</p></div>
               
                
                                
       

                {% empty %}
               

                {% endfor %}  
        
        {% if user in object.tribe.members.all or user.is_superuser or user == object.tribe.chief %}
            <div class="comment_container mt-2">
                
                <form role="form" action = "{% url 'tribe:comment' tribe_id=object.tribe.id playlist_id=object.id song_id=song.id  %}" method="POST" >
                        {% csrf_token %}
                    <div > 
                            <textarea style="font-size:18px; margin-left:2%;" cols="60" rows="1"  type="text" name="text" maxlength="500" required placeholder="Enter words!"></textarea> 
                           
                        <button style="font-size:18px; margin-left:4%;" class="btn btn-primary btn-sm mt-1 mb-1" type="submit">Comment</button>
                    </div>
                    
                </form>
               
            </div>
            
        {% endif %}
       
    </div>
</div>
    {% empty %}
    No songs added yet
{% endfor %}

   </article>

<script>
 $(document).ready(function(){
          $(".show").click(function(){
           $('.comments_section').slideToggle();
          
          });

      });
      $(document).ready(function(){
          $(".close").click(function(){
           $('.comments_section').slideToggle();
          
          });

      });      
</script>

   

{% endblock content %}

{% block list %}
{% endblock %}
{% block chat %}
{% endblock %}

Music Tribes/Tribes/templates/Tribes/tribes_detail.html
{% extends "Tribes/base.html" %}


{% block content %}

   <article class="media content-section">
     <img class="rounded-circle article-img" src="{{ object.image.url }}" >
       <div class="media-body">
         <div class="article-metadata">
           <a class="mr-2" >Chief: {{ object.chief }}</a>
          
          {% if user in object.members.all %}
          <img class="rounded-circle article-img" style="width:3%; height: 3%;" src="/media/join-logo.jpg" ><b>Joined</b>
          {% elif user == object.chief %}
          <b>My Tribe</b>
          {% else %}
            {% if user.is_authenticated %}
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'tribe:join' object.id %}" >Join</a>
            {% endif %}
          {% endif %}
           {% if object.chief == user or user.is_staff %}
           <div>
                <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'tribe:update' object.id %}" >Update</a>
                <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'tribe:delete' object.id %}">Delete</a>
            </div>
           {% endif %}
           {% if user in object.members.all  %}
           <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'tribe:leave' object.id %}" >Leave</a>
           {% endif %}
         </div>
         <h2 class="article-title" >Tribe: <b>{{ object.title }}</b></h2>
         <p class="article-content">Genre: <b>{{ object.genre }}</b></p>
         
         {% if user == object.chief or user.is_staff %}
         <a class="btn btn-primary btn-sm mt-1 mb-1" href="{% url 'tribe:create-playlist' pk=object.id %}" >Add Playlist</a>
         {% endif %}
         {% for playlist in object.playlist_set.all %}
         <h2>
         <a class="article-title" style="font-size: 25px;" href="{% url 'tribe:playlist' playlist.id %}">Playlist: {{ playlist.name }}</a>
          {% if user == object.chief or user.is_staff %}
          <a class="btn btn-secondary btn-sm mt-1 mb-1" href="{% url 'tribe:update-playlist' playlist.id %}" >Update</a>
          <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'tribe:delete-playlist' playlist.id %}" >Delete</a>
          {% endif %}
         </h2>
         <p class="article-content">{{ playlist.description }}</p>
         {% endfor %}
       </div>
       
   </article>
  
   
{% endblock content %}

{% block list %}
<div class="col-md-4">
  <div class="content-section">
    <h3>{{ object.title }}</h3>
    <p class='text-muted'>Members of this tribe.
      <ul class="list-group">

        <a class="list-group-item list-group-item-light"><b>Chieftain: {{ object.chief }}</b></a>
        {% for membership in object.membership_set.all %}
        <div>
        <div class="list-group-item list-group-item-light">Member: {{ membership.person }}
          {% if user == object.chief or user.is_staff %}
        <a class="btn btn-danger btn-sm mt-1 mb-1" href="{% url 'tribe:kick' id1=membership.person.id id2=object.id  %}">Kick</a>
        
        {% endif %}
        </div>
        
        </div>
       {% endfor %}
       
      </ul>
    </p>
  </div>
</div>
<div>


{% endblock %}

{% block chat %}
<div id="left_side" class="col-md-4" ">
		
</div>
<div id="right_side"  >
  <ul id="out" class="" style=" white-space: wrap; width: 380px;height: 700px ;overflow: auto;position: fixed;top: 80px;left: 0px;">
    <p><b>Chat</b></p>
    {% for object in object_list %}
 
      {# prikaz za sve #}
      <li class="list-group-item list-group-item-light" ">
        {% if object.sender == object.receiver.chief %}
        <p style="color: black;" >
          <img class="rounded-circle account-img"style="width:30px; height:30px;" src="{{ object.sender.profile.image.url }}">
          <b>Chief: </b>{{ object.sender }} at {{ object.created_time }}
        </p>{% else %}
        
        
        <p style="color: black;" >
          
          <img class="rounded-circle account-img"style="width:30px; height:30px;" src="{{ object.sender.profile.image.url }}">
          
          Member: {{ object.sender }} at {{ object.created_time }}
        </p>
        {% endif %}
        <div class="list-group-item list-group-item-light text-muted" style="word-wrap: break-word;background-color: #C8C6C6;">
          {% if user == object.receiver.chief or user.is_staff %}
          <a   href="{% url 'tribe:delete-msg' id2=object.receiver.id id1=object.sender.id text=object.text %}" >
            <img style="width: 20px;height: 20px;" src="/media/icon-delete.jpg" >
          </a>
          {% endif %}
          {{ object.text }}
        </div>
        
      </li>
    {% endfor %}
    
    
  {% if user in object.members.all  %}
  <div id="chat-wrapper" class="content-section">
    <div id="chat-list"></div>
    <form id="chat_text_input" action="{% url 'tribe:chat_conversation' object.id %}" method="post">
      {% csrf_token %}
      <br>
      <textarea name="text" id="" cols="30" rows="2"></textarea>
      <input type="submit" class="btn btn-secondary btn-sm mt-1 mb-1">
    </form>
  </div>
</ul>
  {% elif user == object.chief or user.is_staff %}
  <div id="chat-wrapper" class="content-section">
    <div id="chat-list"></div>
    <form id="chat_text_input" action="{% url 'tribe:chat_conversation' object.id %}" method="post">
      {% csrf_token %}
      <textarea name="text" id="" cols="30" rows="2"></textarea>
      <input type="submit" class="btn btn-secondary btn-sm mt-1 mb-1" value="Send">
    </form>
  </div>
  
  {% endif %}
</div>	
</div>
<script>
var objDiv = document.getElementById("out");
objDiv.scrollTop = objDiv.scrollHeight;
</script>

{% endblock %}